import {Geist, Geist_Mono, Montserrat} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Providers from "@/components/Providers/Providers";
import MultiModal from "@/components/MultiModal/MultiModal";
import Overlay from "@/components/Overlay/Overlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'], // для поддержки кириллицы
  weight: ['400', '500', '600', '700'], // нужные веса
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
      <Providers>
        <Header />
        <MultiModal />
        <Overlay />
        {children}
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
